### ISSUE TITLE
support for heroku-24

### ISSUE THREAD

**Issue by jwhitcraft** [heroku/buildpacks-procfile#243]
Hello,

Was just testing this out today and noticed this error when trying to setup a clusterbuilder with kapck:

```
 lastTransitionTime: 2024-10-11T21:51:22Z
    message: "validating buildpack heroku/procfile@3.1.2: stack heroku-24 is not
      supported"
    reason: ReconcileFailed
    status: "False"
```

**Comment by edmorley** [comment]
@jwhitcraft Hi! Thank you for filing an issue. As far as I'm aware this buildpack defines all the correct compatibility metadata according to the Buildpack API spec, so this might be a bug in `lifecycle` / kpack or a case of using an incompatible Platform API version.

What builder image are you using with the `heroku/procfile` CNB? `heroku/builder:24` or a custom builder? If a Heroku builder, is the image up to date? If a custom builder, what version of `lifecycle` is specified in that builder's manifest?

For kpack, what kpack version is it, and do you know what Platform API version it is using?

**Comment by edmorley** [comment]
Oh and what OS/arch is being used?

**Comment by jwhitcraft** [comment]
Hello!

No custom builder here yet, but we are building for `x86_64` arch and `linux`

Here is my ClusterStack

```
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: heroku-24
spec:
  buildImage:
    image: public.ecr.aws/heroku/heroku:24-build
  id: heroku-24
  runImage:
    image: public.ecr.aws/heroku/heroku:24
```

Here is my ClusterStore
```
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: heroku-24
spec:
  sources:
    - image: heroku/buildpack-nodejs:3.2.15
    - image: heroku/buildpack-procfile:3.1.2
```

And here is my ClusterBuilder

```
apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: heroku-24
spec:
  order:
    - group:
        - id: heroku/nodejs
        - id: heroku/procfile
  serviceAccountRef:
    name: kpack
    namespace: kpack
  stack:
    kind: ClusterStack
    name: heroku-24
  store:
    kind: ClusterStore
    name: heroku-24
  tag: my-cluster-build
  additionalLabels:
    io.buildpacks.base.distro.name: "ubuntu"
    io.buildpacks.base.distro.version: "24.04"
```
